[package]
name = "despero"
version = "0.0.1"
authors = ["Koncepto Sociala"]
edition = "2021"
homepage = "https://konceptosociala.eu.org/despero"
repository = "https://github.com/konceptosociala/despero"

[dependencies]
# Misc
colored 	= "2.0.0"
nalgebra 	= "0.31.2"
readonly 	= "0.2.3"
thiserror 	= "1.0.38"

# Rendering
ash 				= "0.37.0"
ash-window 			= "0.11.0"
gpu-allocator	 	= "0.20.0"
image 				= "0.24.5"
raw-window-handle 	= "0.4.2"
tobj				= "3.2.3"
vk-shader-macros 	= "0.2.8"
winit 				= "0.26.0"

# ECS
bus 			= "2.3.0"
hecs 			= "0.7.7"
hecs-schedule 	= "0.6.2"
hecs-hierarchy 	= "0.11.7"
hecs-query-tracker = { path = "hecs-query-tracker" }

# Physics
rapier3d = "0.16.1"

# UI
egui = "0.19.0"

# Scripting
mlua = { version = "0.8.6", features = ["lua51"] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
