[book]
title = "Flatbox Manual"
authors = ["Koncepto Sociala"]
description = "An official manual book for Flatbox engine"
multilingual = true
language = "en"

[rust]
edition = "2021"

[build]
build-dir = "../docs"
create-missing = false
use-default-preprocessors = true
