[package]
name = "sonja-macros"
version = "0.2.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.26", features = ["full", "extra-traits"] }
quote = "1.0.31"
darling = "0.20.3"
proc-macro2 = "1.0.66"
